### ISSUE TITLE
Update jinjs version to pick up 'elif' support

### ISSUE THREAD

**Issue by corbinbs** [ericclemmons/jinja.js#1]
Thanks for jinja.js!

I've been using it to render some existing jinja macros that used the {% if %} {%elif %} {% endif %}
syntax.  The current version of jinja.js didn't seem to like the 'elif' though.   Traced it back to jinjs and added support for it here:
https://github.com/ravelsoft/node-jinjs/commit/025e8f77757000114e926a94831ac3da4d3a73e4

I'm using a custom build now for my work but thought others might like to be able to use 'elif' like they can on the server side. 
When a new version of jinjs is published, please consider updating to it to pick up the 'elif' support.

Thanks!

**Comment by ericclemmons** [comment]
I completely broke my own workflow with Git+Github to do this, but I made some changes for you here:

https://github.com/ericclemmons/jinja.js/compare/a8dca4148244b1c09c8228ddbac8f87631ce00a4...29c1279f87029b886207cbbb8b00c9a8df94630c

In short, `./bin/build` should _always_ pull the latest Jinjs and recompile `jinja.js` for you.

I also added a quick test for you, too: https://github.com/ericclemmons/jinja.js/blob/29c1279f87029b886207cbbb8b00c9a8df94630c/tests/05-if-elif.html

Thanks!
